services:
  db:
    image: postgres:18
    container_name: LeilaoExperience
    environment:
      - POSTGRES_USER= leilao
      - POSTGRES_PASSWORD= 123
      - POSTGRES_DB= leilao_db
    ports:
      - "5425:5432"
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
